name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm2-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libxss-dev libasound2-dev

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build:linux

    - name: List build artifacts
      run: |
        echo "Listing electron-dist directory:"
        ls -la electron-dist/ || echo "electron-dist directory not found"
        echo "Looking for AppImage and deb files:"
        find . -name "*.AppImage" -o -name "*.deb" || echo "No AppImage or deb files found"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          electron-dist/Daily Focus Nest-*.AppImage
          electron-dist/*_amd64.deb
        generate_release_notes: true
        draft: false
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
